# -*- coding: utf-8 -*-
"""rl7minicar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLYaKY5xQHcAOrpzPO-l4bdz08y7-HXd
"""

# 강화학습으로 미니카 학습 모델 생성 + 에니메이션 <== DQN
# MiniCar : (x, y, theta, 속도)의 상태를 가짐, action은 3가지(좌회전, 직진, 우회전)
# 보상은 중앙에서 멀어질수록 불이익. 목표 도착시 보상 +10, 도로 이탈 시 보상 -10
# 현재 정책학습은 main-model이 담당, 안정적인 목표값 제공은 target-model이 담당
# 메모리 버퍼에 경험을 저장하고 샘플링하여 학습(경험 재사용)

!pip install gymnasium

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib import animation
from tensorflow import keras
from collections import deque
import random
import gymnasium as gym
from gymnasium import spaces

# 사용자 정의 환경
class MiniCarEnv(gym.Env):
    def __init__(self) -> None:
        super(MiniCarEnv, self).__init__()
        # 상태 공간
        self.observation_space = spaces.Box(
            low = np.array([0, 0, -np.pi, 0], dtype=np.float32),
            high = np.array([100, 100, np.pi, 5], dtype=np.float32))

        # 행동 공간 : 0 - 좌회전, 1 - 직진, 2 - 우회전
        self.action_space = spaces.Discrete(3)
        self.reset()

    def reset(self, seed=None, options = None):
        x = 10.0
        y = 50.0
        theta = 0.0
        v = 1.0
        self.state = np.array([x, y, theta, v])
        return self.state, {}

    def step(self, action):
        x, y, theta, v = self.state.astype(np.float32)

        # 조향 갱신
        steer_step = 0.1
        if action == 0:   # 왼쪽
            theta -= steer_step
        elif action == 2:   # 오른쪽
            theta += steer_step

        theta *= 0.98   # 조향 감쇠(자연스럽게 직진으로 돌아옴)

        # 각도 wrapping : 각도를 항상 [-π, +π](-180도 ~ 180도) 범위 안에 맞추기 - 각도 정규화
        theta = (theta + np.pi) % (2 * np.pi) - np.pi

        # 이동 : 2차원 좌표상에서
        # x축 이동량 : x = x + v * cos(theta)
        # y축 이동량 : y = y + v * sin(theta)
        n = np.random.normal(0, 0.02, size=2)  # 강화학습에 반영할 노이즈(센서오차, 바람, 미끌어짐...)
        x_prev = x
        x = x + v * np.cos(theta) + n[0]
        y = y + v * np.sin(theta) + n[1]

        self.state = np.array([x, y, theta, v], dtype=np.float32)

        # 보상 설계
        # 중앙선에서 벗어날 경우 감점 고려
        center_penalty = -0.05 * abs(y - 50.00)
        # 진행 보상 : 직진 한 만큼 보상 (뒤로/ 옆 억제)
        process = max(0.0, x - x_prev) * 0.8
        # 생존 보상 - 너무 크지 않게
        alive = 0.2

        reward = alive + center_penalty + process

        # 종료 조건
        terminated = False
        truncated = False

        if x > 90 and 0 <= y <= 100:   # 목표 달성인 경우
            reward += 50.0
            terminated = True
        elif not(0 <= x <= 100 and 0 <= y <= 100):
            reward -= 15.0
            terminated = True

        return self.state, float(reward), terminated, truncated, {}

# DQN 모델 생성
def create_dqn(input_dim, output_dim):
    model = keras.Sequential([
        keras.layers.Input(shape=(input_dim, )),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(output_dim, activation='linear')
    ])
    model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001), loss='mse')
    return model

# 실험 설정
episodes = 100
runs = 1   # 전체 학습을 몇 번 반복할 지 설정  2 ~ 3 을 권장

all_run_rewards = []    # 에피소드별 총 보상 저장
all_run_deviations = [] # 도로 중앙(y=50)으로 부터 평균 편차 저장
final_trajectories = [] # 에피소드별 이동 경로를 저장

# 학습 - 강화학습의 특성(무작위)상 여러번 실행해 평균 성능을 확인하길 권장
for run in range(runs):
    env = MiniCarEnv()
    state_dim = int(env.observation_space.shape[0])   # 관측 차원 수 : 4
    num_actions = int(env.action_space.n)     # 가능한 행동 수 : 3
    model = create_dqn(state_dim, num_actions)   # main model (Main Network)
    target_model = create_dqn(state_dim, num_actions)   # target model (Target Network)
    target_model.set_weights(model.get_weights())
    # model : 현재 Q값을 예측하고 학습하는 신경망
    # target_model : 비교 기준이 되는 고정된 Q값을 제공(학습 목표값 계산에 사용)

    # 하이퍼 파라미터 설정
    gamma = 0.99
    epsilon = 0.6
    epsilon_decay = 0.997
    epsilon_min = 0.02

    batch_size = 32   # 경험을 32개씩 샘플링해서 학습
    memory = deque(maxlen=2000)  # ReplayBuffer 크기

    reward_history = []  # 에피소드 마다 받은 총보상을 저장
    deviation_history = [] # 주행 중 y값이 도로중심에서 얼마나 벗어났는지 평균펀차 저장
    run_trajectories = []

    CENTER_Y = 50.0

    for ep in range(episodes):
        state, _ = env.reset()
        print(f'Run {run} 에피소드 시작 : ep = {ep}, 초기 상태={state}')

        total_reward = 0
        trajectory = []
        done = False

        for step in range(200):
            state_input = np.reshape(state, [1, state_dim])  # 1차원 -> 2차원

            # 탐험, 이용 결정
            if np.random.rand() < epsilon:
                action = np.random.choice(num_actions)
            else:
                q_values = model.predict(state_input, verbose=0)
                action = np.argmax(q_values[0])

            next_state, reward, done, _, _ = env.step(action)
            memory.append((state, action, reward, next_state, done))

            # 경로 및 보상 누적
            trajectory.append(state)
            total_reward += reward
            state = next_state
            if done: break

        # 하나의 메피소드가 끝난 뒤, 그 동안의 성과(보상, 이동경로, 편차 등)를 기록
        reward_history.append(total_reward)
        traj = np.array(trajectory)   # 이동경로 배열로 변환 (벡터 연산 가능)
        mean_deviation = np.mean(np.abs(traj[:, 1] - CENTER_Y))  # 평규 편차 계산

        deviation_history.append(mean_deviation)
        run_trajectories.append((ep, trajectory.copy())) # 이동 경로 저장
        print(f'Run {run} 에피소드 종료 : ep={ep}, \
              총보상=[total_reward:.2f], 편차={mean_deviation:.2f}, 종료상태={state}')

        # 메모리에서 무작위 샘플링 후 Q-netwok 갱신
        if len(memory) >= batch_size:
            minibatch = random.sample(memory, batch_size)

            states, targets = [], []  # 학습에 사용할 입력(states)과 목표값(targets) 누적용

            # 각 샘플에 대해 Q값 계산
            for s, a, r, s_next, d in minibatch:
                s_input = np.reshape(s, [1, state_dim])
                s_next_input = np.reshape(s_next, [1, state_dim])

                target = model.predict(s_input, verbose=0)[0]  # 현재 상태s 에서 각 행동의 Q값을 예측

                if d:
                    target[a] = r   # 종료된 상태면 단순히 보상이 정답
                else:
                    t_next = target_model.predict(s_next_input, verbose=0)[0]  # target_model로 다음 상태의 Q값을 예측
                    target[a] = r + gamma * np.max(t_next)

                # 학습 입력/타겟 누적
                states.append(s)
                targets.append(target)

            # Q-Network 학습
            model.fit(np.array(states), np.array(targets), epochs=1, verbose=0)

        if epsilon > epsilon_min:
            epsilon *= epsilon_decay

        if ep % 10 == 0:   # target network 갱신
            target_model.set_weights(model.get_weights())

    # 하나의 run 안에서 각 에피소드별 보상
    all_run_rewards.append(reward_history)
    all_run_deviations.append(deviation_history)

    if run == runs - 1:   # 마지막 run의 경로 데이터 저장
        final_trajectories = run_trajectories



# 참고  : 각도 wrapping  ----------------
def wrap_angle(theta):
    return (theta + np.pi) % (2 * np.pi) - np.pi

angle = np.deg2rad(370)    # 10
angle = np.deg2rad(-190)   # 170
angle = np.deg2rad(120)   # 170
print(np.rad2deg(wrap_angle(angle)))